"""CARC, RARC, claim status, and adjustment group code dictionaries."""

# Claim Adjustment Group Codes
GROUP_CODES = {
    "CO": "Contractual Obligation",
    "CR": "Correction/Reversal",
    "OA": "Other Adjustment",
    "PI": "Payer Initiated Reduction",
    "PR": "Patient Responsibility",
}

# Claim Status Codes (CLP02)
CLAIM_STATUS_CODES = {
    "1": "Processed as Primary",
    "2": "Processed as Secondary",
    "3": "Processed as Tertiary",
    "4": "Denied",
    "19": "Processed as Primary, Forwarded",
    "20": "Processed as Secondary, Forwarded",
    "21": "Processed as Tertiary, Forwarded",
    "22": "Reversal of Previous Payment",
    "23": "Not Our Claim, Forwarded",
    "25": "Predetermination Pricing Only",
}

# Claim Adjustment Reason Codes (CARC) — common codes
CARC_CODES = {
    "1": "Deductible amount",
    "2": "Coinsurance amount",
    "3": "Co-payment amount",
    "4": "The procedure code is inconsistent with the modifier used",
    "5": "The procedure code/bill type is inconsistent with the place of service",
    "6": "The procedure/revenue code is inconsistent with the patient's age",
    "7": "The procedure/revenue code is inconsistent with the patient's gender",
    "8": "The procedure code is inconsistent with the provider type/specialty",
    "9": "The diagnosis is inconsistent with the patient's age",
    "10": "The diagnosis is inconsistent with the patient's gender",
    "11": "The diagnosis is inconsistent with the procedure",
    "12": "The diagnosis is inconsistent with the provider type",
    "13": "The date of death precedes the date of service",
    "14": "The date of birth follows the date of service",
    "15": "Authorization number not found/not on file",
    "16": "Claim/service lacks information or has submission/billing error(s)",
    "17": "Requested information was not provided or was insufficient/incomplete",
    "18": "Exact duplicate claim/service",
    "19": "This is a work-related injury/illness and thus the liability of the Worker's Compensation Carrier",
    "20": "This injury/illness is covered by the liability carrier",
    "21": "This injury/illness is the liability of the no-fault carrier",
    "22": "This care may be covered by another payer per coordination of benefits",
    "23": "The impact of prior payer(s) adjudication including payments and/or adjustments",
    "24": "Charges are covered under a capitation agreement/managed care plan",
    "25": "Payment denied. Your stop loss deductible has not been met",
    "26": "Expenses incurred prior to coverage",
    "27": "Expenses incurred after coverage terminated",
    "29": "The time limit for filing has expired",
    "30": "Payment adjusted because the patient has not met the required eligibility",
    "31": "Patient cannot be identified as our insured",
    "32": "Our records indicate that this dependent is not an eligible dependent",
    "33": "Insured has no dependent coverage",
    "34": "Insured has no coverage for newborns",
    "35": "Lifetime benefit maximum has been reached",
    "39": "Services denied at the time authorization/pre-certification was requested",
    "40": "Charges do not meet qualifications for emergent/urgent care",
    "44": "Prompt-pay discount",
    "45": "Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement",
    "49": "This is a non-covered service because it is a routine/preventive exam",
    "50": "These are non-covered services because this is not deemed a 'medical necessity'",
    "51": "These are non-covered services because this is a pre-existing condition",
    "53": "Services by an immediate relative or a member of the same household are not covered",
    "54": "Multiple physicians/assistants are not covered in this case",
    "55": "Procedure/treatment/drug is deemed experimental/investigational",
    "56": "Procedure/treatment has not been deemed 'proven to be effective'",
    "58": "Treatment was deemed by the payer to have been rendered in an inappropriate setting",
    "59": "Processed based on multiple or concurrent procedure rules",
    "66": "Blood Deductible",
    "69": "Day outlier amount",
    "70": "Cost outlier — Loss in excess of any applicable deductible amount",
    "89": "Services not provided or authorized by designated provider",
    "90": "Ingredient cost adjustment",
    "94": "Processed in Excess of charges",
    "95": "Plan procedures not followed",
    "96": "Non-covered charge(s)",
    "97": "The benefit for this service is included in the payment/allowance for another service",
    "100": "Payment made to patient/insured/responsible party",
    "101": "Predetermination: anticipated payment upon completion of services",
    "102": "Major Medical Adjustment",
    "103": "Provider promotional discount",
    "104": "Managed care withholding",
    "105": "Tax withholding",
    "106": "Patient payment option/election not in effect",
    "107": "The related or qualifying claim/service was not identified on this claim",
    "108": "Rent/purchase guidelines were not met",
    "109": "Claim/service not covered by this payer/contractor",
    "110": "Billing date predates service date",
    "111": "Not covered unless the provider accepts assignment",
    "112": "Service not furnished directly to the patient and/or not documented",
    "114": "Procedure/product not approved by the Food and Drug Administration",
    "115": "Procedure postponed, canceled, or delayed",
    "116": "The advance indemnification notice signed by the patient did not comply with requirements",
    "117": "Transportation is only covered to the closest facility",
    "118": "ESRD network  support  adjustment",
    "119": "Benefit maximum for this time period or occurrence has been reached",
    "121": "Indemnification adjustment",
    "122": "Psychiatric reduction",
    "125": "Submission/billing error(s)",
    "128": "Newborn's services are covered in the mother's Allowance",
    "129": "Prior processing information appears incorrect",
    "130": "Claim submission fee",
    "131": "Claim specific negotiated discount",
    "132": "Prearranged demonstration project adjustment",
    "133": "The disposition of this claim/service is pending further review",
    "134": "Technical fees removed from charges",
    "135": "Interim bill adjustment",
    "136": "Failure to follow prior payer's coverage rules",
    "137": "Regulatory Surcharges, Assessments, Allowances or Health Related Tax",
    "138": "Appeal procedures not followed or time limits not met",
    "139": "Contracted funding agreement",
    "140": "Patient/Insured health identification number and target name do not match",
    "142": "Monthly Medicaid patient liability amount",
    "143": "Incentive adjustment",
    "144": "Provider network/plan error",
    "146": "Diagnosis was invalid for the date(s) of service",
    "147": "Provider contracted/negotiated rate expired or not on file",
    "148": "Information from another provider was not provided",
    "149": "Lifetime benefit maximum has been reached for this service/benefit category",
    "150": "Payer deems the information submitted does not support this level of service",
    "151": "Payment adjusted because the payer deems the information submitted does not support this many services",
    "152": "Payer deems the information submitted does not support this length of service",
    "153": "Payer deems the information submitted does not support this dosage",
    "154": "Payer deems the information submitted does not support this day's supply",
    "155": "Patient refused the service/procedure",
    "157": "Service/procedure was provided as a result of an act of war",
    "158": "Service/procedure was provided outside of the United States",
    "159": "Service/procedure was provided as a result of terrorism",
    "160": "Injury/illness was the result of an activity that is a benefit exclusion",
    "161": "Provider performance bonus",
    "162": "State-mandated Requirement for Property and Casualty",
    "163": "Attachment/other documentation referenced on the claim was not received",
    "164": "Attachment/other documentation referenced on the claim was not received in a timely fashion",
    "165": "Referral absent or exceeded",
    "166": "These services were submitted after this payer's responsibility for processing",
    "167": "This (these) diagnosis(es) is (are) not covered",
    "169": "Alternate benefit has been provided",
    "170": "Payment is denied when performed/billed by this type of provider",
    "171": "Payment is denied when performed/billed by this type of provider in this type of facility",
    "172": "Payment is adjusted when performed/billed by a provider of this specialty",
    "173": "Service/equipment was not prescribed by a physician",
    "174": "Service was not prescribed prior to delivery",
    "175": "Prescription is incomplete",
    "176": "Prescription is not current",
    "177": "Patient has not met the required eligibility requirements",
    "178": "Patient has not met the required spend down requirements",
    "179": "Services not provided by network/primary care providers",
    "180": "Patient has not met the required waiting requirements",
    "181": "Procedure code was invalid on the date of service",
    "182": "Procedure modifier was invalid on the date of service",
    "183": "The referring provider is not eligible to refer the service billed",
    "184": "The prescribing/ordering provider is not eligible",
    "185": "The rendering provider is not eligible to perform/render",
    "186": "Level of care change adjustment",
    "187": "Consumer Directed/Consumer Driven Health Plan",
    "188": "This product/procedure is only covered when used according to FDA recommendations",
    "189": "Not otherwise classified (NOC) procedure",
    "190": "Payment is included in the allowance for a Skilled Nursing Facility",
    "192": "Non standard adjustment code from paper remittance",
    "193": "Original payment decision is being maintained",
    "194": "Anesthesia performed by the operating physician, the## assistant surgeon, or other",
    "195": "Refund issued to an erroneous priority payer for this claim/service",
    "197": "Precertification/authorization/notification/pre-treatment absent",
    "198": "Precertification/authorization exceeded",
    "199": "Revenue code and Procedure code do not agree",
    "200": "Expenses incurred during lapse in coverage",
    "201": "Workers' Compensation case settled. Patient is responsible for amount of this claim/service",
    "202": "Non-covered personal comfort or convenience items",
    "203": "Discontinued or reduced service",
    "204": "This service/equipment/drug is not covered under the patient's current benefit plan",
    "205": "Pharmacy discount",
    "206": "National Provider Identifier - missing",
    "207": "National Provider Identifier - Invalid format",
    "208": "National Provider Identifier - Not matched",
    "209": "Per regulatory requirement, this claim has been adjusted",
    "210": "Pre-Admission Testing reduction",
    "211": "National Drug Codes (NDC) not eligible for rebate",
    "212": "Administrative surcharges are not covered",
    "213": "Non-compliance with the physician at the time of initial evaluation",
    "215": "Based on subrogation of a third party settlement",
    "216": "Based on the findings of a review organization",
    "219": "Based on extent of injury",
    "222": "Exceeds the contracted maximum number of hours/days/units",
    "223": "Adjustment code for mandated federal, state or local law/regulation",
    "224": "Patient identification compromised by a reported identity theft",
    "225": "Penalty or Regulatory Fee based on a standard of practice violation",
    "226": "Information requested from the Billing/Rendering Provider was not provided",
    "227": "Information requested from the patient/insured/responsible party was not provided",
    "228": "Denied based on a demonstration/clinical trial",
    "229": "Partial charge amount not considered by Medicare due to the initial claim determination",
    "230": "No available or valid peer or state-specific benchmarking data to support the claim",
    "231": "Mutually exclusive procedures cannot be done in the same day/setting",
    "232": "Institutional Transfer Amount",
    "233": "Services/charges related to the treatment of a hospital-acquired condition or preventable medical error",
    "234": "This procedure is not paid separately",
    "235": "Sales Tax",
    "236": "This procedure or procedure/modifier combination is not compatible with another procedure previously submitted",
    "237": "Legislative/Regulatory Penalty",
    "238": "Claim spans ineligible and eligible periods of coverage",
    "239": "Claim spans benefit package groups",
    "240": "Car liability insurance is primary",
    "241": "This claim was submitted for the wrong insurance type",
    "242": "Services not provided by authorized network providers",
    "243": "Services not authorized by network/primary care providers",
    "245": "Provider performance program  withhold",
    "246": "This non-payable code is for required reporting only",
    "247": "Deductible for Professional services",
    "248": "Sequestration adjustment",
    "249": "This claim has been identified as a readmission",
    "250": "The attachment/other documentation that was received was incomplete or deficient",
    "251": "The attachment/other documentation that was received was illegible",
    "252": "An attachment/other documentation is required to adjudicate this claim",
    "253": "Sequestration — Loss in excess of federal debt",
    "254": "Inappropriate claim submission",
    "256": "Service not payable per managed care contract",
    "257": "The disposition of the claim/service is undetermined during the premium payment grace period",
    "258": "Claim/service not covered when patient is in custody/incarceration",
    "259": "Additional payment for delivery type",
    "260": "Processed under Medicaid ACA Enhanced Fee schedule",
    "261": "The procedure or service is inconsistent with the provider type/specialty",
    "262": "Adjustment for delivery type",
    "263": "Adjustment for anesthesia service",
    "264": "Premium payment",
    "265": "Transfer adjustment",
    "266": "Discount adjustment",
    "267": "Claim/service denied, appealed and approved",
    "268": "National Provider Identifier — Organization",
    "269": "Charge exceeds the maximum allowable amount per plan/payer policy",
    "270": "Claim received by the dental plan, but benefits not available",
    "271": "Prior contractual reductions related to a current periodic payment",
    "272": "Coverage/program guidelines were not met",
    "273": "Coverage/program guidelines were exceeded",
    "274": "Fee negotiated/allowed amount not on file",
    "275": "Prior Payer's (Insurer) Explanation of Benefits was not submitted",
    "276": "Appeal procedures not established",
    "277": "The disposition of the claim/service is undetermined during the appeal process",
    "278": "Performance program  adjustment",
    "279": "Services not covered when patient is in a Hospice",
    "280": "Claim adjusted based on a Recovery Audit",
    "281": "Prior payer's (insurer's) payment is less than the expected contracted amount",
    "282": "Negative individual stop loss adjustment",
    "283": "Charges billed exceed acceptable threshold",
    "284": "Precertification/authorization/notification/pre-treatment — Loss of eligibility",
    "285": "Appeal procedures not followed",
    "286": "National Provider Identifier (NPI) — Entity Not Eligible",
    "287": "National Provider Identifier (NPI) — Entity Not Found",
    "288": "National Provider Identifier (NPI) — Deactivated",
    "289": "Fee/service not payable — code is designated as non-payable",
    "290": "Claim/service adjusted based on a quality improvement initiative program",
    "291": "Diagnostic test performed by an unauthorized provider",
    "292": "Service not furnished by a designated provider",
    "293": "Claim/service adjusted based on a Bundled Payment arrangement",
    "294": "Claim/service adjusted based on a value-based reimbursement arrangement",
}

# Remittance Advice Remark Codes (RARC) — common codes
RARC_CODES = {
    "M1": "X-ray not taken within the prescribed time frames",
    "M2": "Not paid separately when the patient is an inpatient",
    "M3": "Equipment is the same or similar to equipment already being used",
    "M4": "Alert: This is the first monthly installment payment for this durable medical equipment",
    "M5": "Monthly rental payments can continue until the earlier of the estimated months or until returned",
    "M6": "Alert: You must furnish and service rented capped rental DME",
    "M7": "Claim/service not covered when patient is in custody",
    "M8": "Alert: This is the second monthly installment",
    "M9": "An observation/evaluation and management service was furnished",
    "M10": "Alert: Patient eligible and is enrolled in Part B",
    "M11": "DME, orthotics and prosthetics must be billed to the DME carrier",
    "M12": "Diagnostic tests performed by a physician must indicate the purchased price",
    "M13": "Only one initial visit is covered per specialty per medical group",
    "M14": "No separate payment for services rendered to hospital inpatients or outpatients",
    "M15": "Separately billed services/tests have been bundled as they are considered components",
    "M16": "Alert: Please see our web site, mailings, or bulletins for more details",
    "M17": "Alert: Payment approved as you did not know, and could not reasonably have been expected to know",
    "M18": "Certain fields must be completed with valid information per state/federal regulations",
    "M19": "Missing/incomplete/invalid physical condition of patient",
    "M20": "Missing/incomplete/invalid oxygen certification/re-certification",
    "M21": "Missing/incomplete/invalid Medical Record Number",
    "M22": "Missing/incomplete/invalid next office visit date",
    "M23": "Missing/incomplete/invalid exercise minutes",
    "M24": "Missing/incomplete/invalid number of sessions",
    "M25": "The information furnished does not substantiate the need for this level of service",
    "M26": "Alert: The acute inpatient PPS case-mix index changed effective on the date shown",
    "M27": "The patient has been relieved of liability",
    "M30": "Missing/incomplete/invalid type of bill",
    "M31": "Missing/incomplete/invalid beginning date of service",
    "M32": "Missing/incomplete/invalid item description/HCPCS",
    "M36": "We are unable to process this claim/service",
    "M37": "Alert: Service is subject to the SNF consolidated billing provisions",
    "M38": "Alert: The patient is liable for the charges for this service",
    "M39": "Alert: The patient is not liable for payment for this service",
    "M40": "Claim must be assigned and singed by the physician",
    "M44": "Missing/incomplete/invalid condition code",
    "M45": "Missing/incomplete/invalid occurrence date(s)",
    "M46": "Missing/incomplete/invalid occurrence span date(s)",
    "M47": "Missing/incomplete/invalid internal or document control number",
    "M49": "Missing/incomplete/invalid value amount(s) or code(s)",
    "M50": "Missing/incomplete/invalid revenue code(s)",
    "M51": "Missing/incomplete/invalid procedure code(s)",
    "M52": "Missing/incomplete/invalid 'from' date(s) of service",
    "M53": "Missing/incomplete/invalid days/units of service",
    "M54": "Missing/incomplete/invalid total charges",
    "M55": "We do not cover chiropractic services rendered by physical therapists",
    "M56": "Missing/incomplete/invalid payer identifier",
    "M57": "Missing/incomplete/invalid provider identifier",
    "M59": "Missing/incomplete/invalid patient relation to insured",
    "M60": "Missing/incomplete/invalid certificate of medical necessity",
    "M61": "Missing/incomplete/invalid clinical information for this service",
    "M62": "Missing/incomplete/invalid treatment authorization code(s)",
    "M64": "Missing/incomplete/invalid other payer information",
    "M65": "One or more of these Services have been processed with an appropriate fee",
    "M66": "Our records indicate that you were advised of the charge reduction for this service",
    "M67": "Alert: Claim was treated as an adjustment to a previously processed claim",
    "M69": "Paid at the regular rate as the service is not a valid test or was not performed by a certified facility",
    "M70": "Alert: You were overpaid for this service. The overpayment has been applied to this claim",
    "M71": "Total payment reduced due to overlap of benefits",
    "M72": "Alert: The patient overpaid you for these assigned benefits",
    "M73": "Alert: You have been overpaid for services",
    "M74": "This payment covers multiple claim determinations",
    "M75": "Multiple automated and manual claim adjustments were necessary",
    "M76": "Missing/incomplete/invalid diagnosis or condition",
    "M77": "Missing/incomplete/invalid place of service",
    "M79": "Alert: Service billed is within the global surgery period of another service",
    "M80": "Missing/incomplete/invalid provider name, address or phone number",
    "M81": "You are required to code to the highest level of specificity",
    "M82": "Missing/incomplete/invalid provider/supplier signature",
    "M83": "Service is not separately payable or a fee cannot be computed",
    "M84": "Premium payment withholding",
    "M85": "Patient interest accrued",
    "M86": "Provider interest accrued",
    "M87": "Refund associated with a previous interest payment",
    "M89": "Services provided outside of the United States have been denied",
    "M90": "Not covered for this diagnosis",
    "MA01": "Alert: If you do not agree with what we approved for these services, you may appeal",
    "MA02": "Alert: If you do not agree with this determination, you have the right to appeal",
    "MA04": "Secondary payment cannot be considered without the identity of the primary payer",
    "MA07": "Alert: The claim information has also been forwarded to Medicaid for review",
    "MA08": "Alert: Information was also sent to the patient regarding the above listed service(s)",
    "MA09": "Alert: Claim submitted as unassigned but processed as assigned",
    "MA10": "Alert: The patient's payment was in excess of the amount owed",
    "MA13": "Alert: You may be subject to penalties if you bill the patient for amounts not reported",
    "MA14": "Alert: The patient is a member of an employer-sponsored prepaid health plan",
    "MA15": "Alert: Your claim has been separated to expedite handling",
    "MA18": "Alert: The claim information is also being forwarded to the patient's supplemental insurer",
    "MA19": "Alert: Information was received concerning the beneficiary's other health insurance",
    "MA20": "Skilled Nursing Facility (SNF) stay not covered when the patient was not admitted",
    "MA22": "Payment of less than the total charges may reflect a special payment arrangement",
    "MA23": "The professional and technical components cannot be billed separately for this procedure",
    "MA24": "Medicare is secondary and you have filed timely",
    "MA25": "You must obtain an individual NPI",
    "MA26": "Alert: Our records indicate that you were previously informed of this policy/procedure",
    "MA27": "Missing/incomplete/invalid entitlement number or SSN",
    "MA28": "Alert: Patient's Medicare ID number on the claim has been changed",
    "MA30": "Missing/incomplete/invalid type of bill for facility claims",
    "MA31": "Alert: The claim has been separated for processing",
    "MA32": "Missing/incomplete/invalid CLIA certification number",
    "MA33": "Alert: The interest payment reflects the number of days from the payment due date",
    "N1": "Alert: You may appeal this decision",
    "N2": "Alert: This report is required by state/federal law",
    "N3": "Missing/incomplete/invalid consent or authorization form",
    "N4": "Missing/incomplete/invalid prior insurance carrier EOB",
    "N5": "Alert: Procedures are included in the inpatient hospital fee",
    "N6": "Alert: Under 30 day transfer review",
    "N7": "Alert: This decision may be appealed by filing a written request",
    "N8": "Facility provider number/NPI is missing/incomplete/invalid",
    "N9": "Adjustment represents collection against receivable created in prior overpayment",
    "N10": "Payment based on the findings of a previous review/audit of this provider",
    "N11": "No additional payment will be made for this claim",
    "N12": "Charges for diagnosis services provided to hospital inpatients by physician",
    "N13": "Payment based on professional component",
    "N14": "Payment based on technical component",
    "N15": "Missing/incomplete/invalid prescriber credentials",
    "N16": "Alert: Please see our web site, mailings, or bulletins for more details",
    "N17": "Alert: Payment has been issued to your employer/group",
    "N19": "Procedure code incidental to primary procedure",
    "N20": "Service not payable with other procedure performed at same time",
    "N21": "Alert: Multiple patients on one claim",
    "N22": "Alert: This determination applies to a recurring monthly service/claim",
    "N23": "Indicates this transaction is a refund/recoupment of a prior payment",
    "N24": "Missing/incomplete/invalid Electronic Funds Transfer (EFT) banking information",
    "N25": "Alert: This claim has been forwarded to the payer of last resort",
    "N26": "Missing/incomplete/invalid mailing address",
    "N27": "Missing/incomplete/invalid first date of the period of confinement",
    "N28": "Not covered based on findings of a previous payer's review",
    "N29": "Missing/incomplete/invalid documentation or orders/referral",
    "N30": "Patient ineligible for this service",
    "N31": "Preexisting condition; not covered",
}


def lookup_carc(code: str) -> str:
    """Look up a CARC code description."""
    return CARC_CODES.get(code, f"Unknown CARC code: {code}")


def lookup_rarc(code: str) -> str:
    """Look up a RARC code description."""
    return RARC_CODES.get(code, f"Unknown RARC code: {code}")


def lookup_group(code: str) -> str:
    """Look up an adjustment group code description."""
    return GROUP_CODES.get(code, f"Unknown group code: {code}")


def lookup_status(code: str) -> str:
    """Look up a claim status code description."""
    return CLAIM_STATUS_CODES.get(code, f"Unknown status code: {code}")
